[package]
name = "kult-browser-backend-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "seed_games"
path = "src/bin/seed_games.rs"

[[bin]]
name = "kult_browser_backend_rust"
path = "src/main.rs"

[[bin]]
name = "seed_leaderboard_config"
path = "src/bin/seed_leaderboard_config.rs"

[[bin]]
name = "test_fetch_leaderboard"
path = "src/bin/test_fetch_leaderboard.rs"

[[bin]]
name = "test_global_leaderboard"
path = "src/bin/test_global_leaderboard.rs"

[[bin]]
name = "test_queue_producer"
path = "src/bin/test_queue_producer.rs"

[[bin]]
name = "moments_worker"
path = "src/bin/moments_worker.rs"

[[bin]]
name = "test_0g_upload"
path = "src/bin/test_0g_upload.rs"

[[bin]]
name = "test_do_download"
path = "src/bin/test_do_download.rs"

[dependencies]
mongodb = "3.1"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
bson = { version = "2", features = ["chrono-0_4"] }
futures = "0.3"
axum = { version = "0.7", features = ["macros"] }
jsonwebtoken = "9.2"
once_cell = "1.21.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
tower-http = { version = "0.5", features = ["trace"] }
nanoid = "0.4"
redis = "0.27"
reqwest = "0.12"
